
import streamlit as st
import pandas as pd
import plotly.express as px

# --------------------------------------------------
# PAGE CONFIGURATION
# --------------------------------------------------

st.set_page_config(
    page_title="Data Storytelling Application",
    page_icon="📊",
    layout="wide"
)

# --------------------------------------------------
# LOAD DATA
# --------------------------------------------------

@st.cache_data
def load_data():
    df = pd.read_csv("sales.csv")

    if "Date" in df.columns:
        df["Date"] = pd.to_datetime(df["Date"])

    return df

df = load_data()

# --------------------------------------------------
# TITLE
# --------------------------------------------------

st.title("📊 Data Storytelling Application")
st.subheader("Supermarket Sales Analysis")

st.markdown("---")

# --------------------------------------------------
# DATASET INTRODUCTION
# --------------------------------------------------

st.header("1. Dataset Introduction")

st.write("""
This dataset contains supermarket transaction records from multiple branches.
The objective of this analysis is to understand customer behavior,
analyze sales performance, identify business trends,
and provide recommendations for improving operations.
""")

col1, col2, col3 = st.columns(3)

with col1:
    st.metric("Total Transactions", len(df))

with col2:
    st.metric("Total Revenue", f"${df['Total'].sum():,.2f}")

with col3:
    st.metric("Average Rating", round(df["Rating"].mean(), 2))

st.subheader("Dataset Preview")
st.dataframe(df.head())

st.markdown("---")

# --------------------------------------------------
# EDA SECTION
# --------------------------------------------------

st.header("2. Exploratory Data Analysis (EDA)")

st.write("""
Exploratory Data Analysis helps identify trends,
patterns, and relationships within the supermarket sales dataset.
""")

# --------------------------------------------------
# STORY 1
# --------------------------------------------------

st.header("3. Finding 1: Revenue by Product Line")

product_sales = (
    df.groupby("Product line")["Total"]
      .sum()
      .reset_index()
      .sort_values("Total", ascending=False)
)

fig1 = px.bar(
    product_sales,
    x="Product line",
    y="Total",
    title="Revenue Generated by Product Line"
)

st.plotly_chart(fig1, use_container_width=True)

top_product = product_sales.iloc[0]["Product line"]

st.success(
    f"Insight: '{top_product}' is the highest revenue-generating product category."
)

st.markdown("---")

# --------------------------------------------------
# STORY 2
# --------------------------------------------------

st.header("4. Finding 2: Branch Performance")

branch_sales = (
    df.groupby("Branch")["Total"]
      .sum()
      .reset_index()
      .sort_values("Total", ascending=False)
)

fig2 = px.bar(
    branch_sales,
    x="Branch",
    y="Total",
    color="Branch",
    title="Revenue by Branch"
)

st.plotly_chart(fig2, use_container_width=True)

best_branch = branch_sales.iloc[0]["Branch"]

st.success(
    f"Insight: Branch {best_branch} generates the highest overall revenue."
)

st.markdown("---")

# --------------------------------------------------
# STORY 3
# --------------------------------------------------

st.header("5. Finding 3: Customer Payment Preferences")

fig3 = px.pie(
    df,
    names="Payment",
    values="Total",
    title="Revenue Distribution by Payment Method"
)

st.plotly_chart(fig3, use_container_width=True)

st.success(
    "Insight: Customers show strong adoption of non-cash payment methods."
)

st.markdown("---")

# --------------------------------------------------
# STORY 4
# --------------------------------------------------

st.header("6. Finding 4: Customer Satisfaction")

fig4 = px.histogram(
    df,
    x="Rating",
    nbins=10,
    title="Distribution of Customer Ratings"
)

st.plotly_chart(fig4, use_container_width=True)

avg_rating = round(df["Rating"].mean(), 2)

st.success(
    f"Insight: The average customer rating is {avg_rating}, indicating generally positive customer experiences."
)

st.markdown("---")

# --------------------------------------------------
# STORY 5
# --------------------------------------------------

st.header("7. Finding 5: Sales Trend Over Time")

daily_sales = (
    df.groupby("Date")["Total"]
      .sum()
      .reset_index()
)

fig5 = px.line(
    daily_sales,
    x="Date",
    y="Total",
    title="Sales Trend Over Time"
)

st.plotly_chart(fig5, use_container_width=True)

st.success(
    "Insight: Sales fluctuate over time, showing periods of higher and lower customer activity."
)

st.markdown("---")

# --------------------------------------------------
# CONCLUSION
# --------------------------------------------------

st.header("8. Final Conclusions & Recommendations")

st.write("""
### Key Findings

1. Some product categories generate significantly higher revenue than others.
2. Branch performance varies across locations.
3. Customers increasingly prefer digital payment options.
4. Customer ratings indicate satisfactory service levels.
5. Sales patterns change over time and should be monitored.

### Recommendations

✅ Increase inventory for top-performing product lines.

✅ Study and replicate successful practices from the best-performing branch.

✅ Continue investing in digital payment infrastructure.

✅ Use customer feedback and ratings to improve service quality.

✅ Monitor sales trends to optimize staffing and inventory management.
""")

st.balloons()
